DROP TABLE IF EXISTS CUSTOMER;
  
CREATE TABLE CUSTOMER (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(80) NOT NULL,
  address VARCHAR(150) NOT NULL,
  dateOfBirth DATE DEFAULT NULL,
  PRIMARY KEY (id)
);